### ISSUE TITLE
state of the repo

### ISSUE THREAD

**Issue by beckmx** [Moballo-LLC/tvOS-Browser#15]
Hello, I was looking at the git history, I'd say is faster to ask, is this repo containing more changes than its original fork? or is behind?

**Comment by Jason-Morcos** [comment]
Running a compare, this repo is still ahead. The other one just updated the readme. Will pull the other changes back to make it clearer.

**Comment by Jason-Morcos** [comment]
Actually looks like I was a few commits behind but I've caught that all up and pushed a new release. Thanks!

**Comment by beckmx** [comment]
Ok, so basically you did all the manual merges from the other, right?

**Comment by Jason-Morcos** [comment]
Yes, I did that, and fixed some issues with the pointer not becoming a cursor when it should, and improved the quality of some of the graphics (notably the cursor)

**Comment by Jason-Morcos** [comment]
Github provides powerful tools for comparing this repo and jvanakker's - you can pull differences from one to the other too see what might be new in one and what the other might be missing. This shows all the things this repo has that the parent repo doesn't:
https://github.com/jvanakker/tvOSBrowser/compare/master...Moballo-LLC:tvOS-Browser:master?expand=1

Versus all the stuff in jvanakker that's not here (nothing):
https://github.com/Moballo-LLC/tvOS-Browser/compare/master...jvanakker:tvOSBrowser:master?expand=1
