### ISSUE TITLE
Does Apple Support tvOS Apps using WebKit?

### ISSUE THREAD

**Issue by EddieBlueUplink** [Moballo-LLC/tvOS-Browser#17]
Hello, I read that WebKit on tvOS is prohibited:
https://stackoverflow.com/questions/32503582/web-app-in-tvos

What is the point if this application won't pass certification?

Thanks,

**Comment by Jason-Morcos** [comment]
The point is to side-load this app so you can use it on your Apple TV! Apple won't allow this on the App Store, but you can still install it yourself.
