### ISSUE TITLE
Compiled .ipa

### ISSUE THREAD

**Issue by MattBryanB** [Moballo-LLC/tvOS-Browser#24]
Hi there! I appreciate all the effort you’ve put into keeping this updated. Unfortunately, I’m no longer using a Mac and can’t access Xcode. Could you please share a compiled .ipa version of this project that I can use instead? It would be incredibly helpful. Thanks a lot!

**Comment by Jason-Morcos** [comment]
Hi, with the way Apple handles distributor, I'm unable to provide IPAs that are installable on your devices
You'll have to find a Mac to be able to install the browser :/
