### ISSUE TITLE
Grey Border Around View

### ISSUE THREAD

**Issue by rasod** [Moballo-LLC/tvOS-Browser#3]
A grey border surrounds the web view.

tvOS 11.2.5

![screen shot 2018-02-06 at 2 33 00 pm](https://user-images.githubusercontent.com/7154349/35879988-a6de0ebe-0b4a-11e8-9e1d-1b2249983031.png)

**Comment by Jason-Morcos** [comment]
I'm not sure why this is occurring. If you or another user can solve the issue, I'm happy to merge it back in! I will investigate further when possible

**Comment by Jason-Morcos** [comment]
Upon further investigation, this appears to be an issue with content offsets/insets within the UIWebView's scroll view. The UIWebView itself is receiving the correct frame and filling the screen.

**Comment by rasod** [comment]
I managed a workaround by scrolling the view after the page loads

**Comment by Jason-Morcos** [comment]
Does that work if scale pages to fit is enabled too?
I found that enabling scale pages to fit made the webpage fit but with a large dead area all around. I believe there is some strange margins frame being loaded into the webview.

**Comment by Jason-Morcos** [comment]
I just released an update with a new "Offset correction" menu option! This option is enabled by default (can go to menu and turn off) and appears to fix the gray border bug. It's a hacky fix but appears to work. If you have a better fix or more issues, feel free to reach out or PR!
